name: "Build Packages for x86_64 Glibc"
# This gh-actions was adopted from https://github.com/Makrennel/hyprland-void/blob/master/.github/workflows/build-x86_64-glibc.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REPO_OWNER: "${{ github.repository_owner }}"
  REPO_NAME: "${{ github.event.repository.name }}"

jobs:
  build:
    name: Build Voidlings
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/void-linux/void-buildroot-${{ matrix.config.libc }}:20240526R1
      options: --platform ${{ matrix.config.platform }}
      env:
        PATH: "/usr/libexec/chroot-git:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin"
        ARCH: "${{ matrix.config.arch }}"
        BOOTSTRAP: "${{ matrix.config.host }}"
        TEST: "${{ matrix.config.test }}"
        HOSTREPO: /hostrepo

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              arch: x86_64,
              host: x86_64,
              libc: glibc,
              platform: linux/amd64,
              test: 1,
            }

    steps:
      - name: Prepare container
        run: |
          mkdir -pv /etc/xbps.d && cp -v /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          xbps-install -Syu xbps || xbps-install -yu xbps
          xbps-install -Syu
          xbps-install -y tar curl

      - name: Clone Void-Packages and prepare
        run: |
          mkdir ~/void-pkgs
          cd ~/void-pkgs
          git clone --depth 1 https://github.com/void-linux/void-packages.git

      - name: Clone main repo
        run: |
          cd ~/void-pkgs
          git clone https://github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}.git

      - name: Copy and prepare for installation
        run: |
          cd ~/void-pkgs
          cd ${{ env.REPO_NAME }}
          mkdir -p srcpkgs/brave-bin
          cd srcpkgs/brave-bin
          pwd
          curl -O https://raw.githubusercontent.com/soanvig/brave-bin/master/template
          cd ~/void-pkgs/${{ env.REPO_NAME }}
          cp -r srcpkgs/* ../void-packages/srcpkgs

      - name: Create hostrepo and prepare masterdir
        run: |
          cd ~/void-pkgs/void-packages
          ln -s "$(pwd)" /hostrepo &&
          common/travis/set_mirror.sh &&
          common/travis/prepare.sh &&
          common/travis/fetch-xtools.sh

      # Common Deps

      # Maintained by soanvig: soanvig/brave-bin
      - name: Build brave-bin
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg brave-bin)

      # Normal Builds
      - name: Build anki-qt6
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg anki-qt6)

      - name: Build bat-extras
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg bat-extras)

      - name: Build bun-bin
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg bun-bin)

      # Fonts
      - name: Build font-cartograph-nonfree
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg font-cartograph-nonfree)

      - name: Build font-comfortaa
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg font-comfortaa)

      - name: Build font-lexend
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg font-lexend)

      - name: Build font-quicksand
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg font-quicksand)

      - name: Build neovide
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg neovide)

      - name: Build qutebrowser-profile
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg qutebrowser-profile)

      # Maintained by void linux team (void-linux/void-packages)
      - name: Build android-studio
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg android-studio)

      - name: Build discord
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg discord)

      - name: Build msttcorefonts
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg msttcorefonts)

      - name: Build zoom
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg zoom)

      # Sometimes xbps-src builds a bunch of other junk I don't want to be liable for distributing
      - name: Copy relevant packages to new directory to be packaged
        run: |
          mkdir ~/packages
          cp ~/hostdir/binpkgs/*.xbps ~/packages
          cp ~/hostdir/binpkgs/nonfree/*.xbps ~/packages
          cd ~/packages
          xbps-rindex -a *

      # Retrieve the signing key from the separate private repository
      - name: Retrieve private key
        run: |
          cd ~
          echo -n "${{ secrets.XBPS_REPOSITORY_KEY }}" > private.pem

      # We need to sign the packages with our private key so that they will be accepted by xbps remotely
      # See: https://docs.voidlinux.org/xbps/repositories/signing.html
      - name: Sign repository
        run: |
          xbps-rindex --privkey ~/private.pem --sign --signedby "${{ env.REPO_NAME }}-github-action" ~/packages
          xbps-rindex --privkey ~/private.pem --sign-pkg ~/packages/*.xbps

      - name: Compress Packages
        run: |
          cd ~/packages
          tar -czvf voidlings.tar.gz *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}
          path: ~/packages/voidlings.tar.gz

  publish:
    name: Pack and Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}
          path: ~/

      - name: Extract Artifact
        run: |
          tar -xvf ~/voidlings.tar.gz -C ./
          rm -v ~/voidlings.tar.gz

      # - name: Upload to Cloudflare R2 Bucket
      #   uses: ryand56/r2-upload-action@latest
      #   with:
      #     r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
      #     r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
      #     r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      #     r2-bucket: ${{ secrets.R2_BUCKET }}
      #     source-dir: ./
      #     destination-dir: ./

      - name: Upload to Cloudflare R2 Bucket
        uses: okkema/github-action-r2@v0.1.1
        with:
          account_id: ${{ secrets.R2_ACCOUNT_ID }}
          r2_access_key: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2_secret_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2_bucket: ${{ secrets.R2_BUCKET }}
          source_dir: ./
          destination_dir: ./
